version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - local-moderation
    networks:
      - moderation-net
    restart: unless-stopped

  local-moderation:
    build:
      context: ./local_moderation_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - moderation-net
    restart: unless-stopped

networks:
  moderation-net:
    driver: bridge
